language: node_js

node_js:
- '10'

env:
- NG_CLI_ANALYTICS=false

script:
- npm run build

notifications:
    email: false

cache:
    directories:
    - node_modules

after_success:
- npm run codecov


